src/accounts/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^login/$', views.LoginView.as_view(), name="login"),
    url(r'^logout/$', views.LogoutView.as_view(), name='logout'),
    url(r'^signup/$', views.SignUpView.as_view(), name='signup'),
    url(r'^password-change/$', views.PasswordChangeView.as_view(),
        name='password-change'),
    url(r'^password-reset/$', views.PasswordResetView.as_view(),
        name='password-reset'),
    url(r'^password-reset-done/$', views.PasswordResetDoneView.as_view(),
        name='password-reset-done'),
    url(r'^password-reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$$',
        views.PasswordResetConfirmView.as_view(),  # NOQA
        name='password-reset-confirm'),
]

src/profiles/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^me$', views.ShowProfile.as_view(), name='show_self'),
    url(r'^me/edit$', views.EditProfile.as_view(), name='edit_self'),
    url(r'^(?P<slug>[\w\-]+)$', views.ShowProfile.as_view(),
        name='show'),
]

src/pynginx/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
import profiles.urls
import accounts.urls
import dashboard.urls
import sites.urls
from . import views

urlpatterns = [
    url(r'^$', views.HomePage.as_view(), name='home'),
    url(r'^about/$', views.AboutPage.as_view(), name='about'),
    url(r'^users/', include(profiles.urls, namespace='profiles')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include(accounts.urls, namespace='accounts')),
    url(r'^dashboard/', include(dashboard.urls, namespace='dashboard')),
    url(r'^sites/', include(sites.urls, namespace='sites')),
]

# User-uploaded files like profile pics need to be served in development
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Include django debug toolbar if DEBUG is on
if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

src/sites/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.SiteIndex.as_view(), name='index'),
    url(r'^create/$', views.SiteCreate.as_view(), name='create_site'),
    url(r'^update/(?P<pk>\d+)/$', views.SiteUpdate.as_view(), name='update_site'),
    url(r'^delete/(?P<pk>\d+)/$', views.SiteDelete.as_view(), name='delete_site'),

]

src/templates/base/partials/_footer.html
{% block footer %}

    <footer class="footer">
        <div class="footer-block buttons">

        </div>
        <div class="footer-block author">
            <ul>
                <li> created by
                    <a href="https://bytesense.co.uk">ByteSense Ltd</a>
                </li>
            </ul>
        </div>
    </footer>

{% endblock %}

src/templates/base/partials/_header.html
{% block header %}

    <header class="header">
        <div class="header-block header-block-collapse d-lg-none d-xl-none">
            <button class="collapse-btn" id="sidebar-collapse-btn">
                <i class="fa fa-bars"></i>
            </button>
        </div>
        <div class="header-block header-block-search">
            <form role="search">
                <div class="input-container">
                    <i class="fa fa-search"></i>
                    <input type="search" placeholder="Search">
                    <div class="underline"></div>
                </div>
            </form>
        </div>
        <div class="header-block header-block-buttons">
            {% if messages %}
                {% for message in messages %}
                    <div class="alert alert-{{ message.tags }} alert-dismissible text-center" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                                aria-hidden="true">&times;</span></button>
                        <strong>{% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Error{% else %}
                            {{ message.tags|title }}{% endif %}!</strong> {{ message }}
                    </div>
                {% endfor %}
            {% endif %}
        </div>
        <div class="header-block header-block-nav">
            <ul class="nav-profile">
                <li class="notifications new">
                    <a href="" data-toggle="dropdown">
                        <i class="fa fa-bell-o"></i>
                        <sup>
                            <span class="counter">8</span>
                        </sup>
                    </a>
                    <div class="dropdown-menu notifications-dropdown-menu">
                        <ul class="notifications-container">
                            <li>
                                <a href="" class="notification-item">
                                    <div class="img-col">
                                        <div class="img" style="background-image: url('assets/faces/3.jpg')"></div>
                                    </div>
                                    <div class="body-col">
                                        <p>
                                            <span class="accent">Zack Alien</span> pushed new commit:
                                            <span class="accent">Fix page load performance issue</span>. </p>
                                    </div>
                                </a>
                            </li>
                            <li>
                                <a href="" class="notification-item">
                                    <div class="img-col">
                                        <div class="img" style="background-image: url('assets/faces/5.jpg')"></div>
                                    </div>
                                    <div class="body-col">
                                        <p>
                                            <span class="accent">Amaya Hatsumi</span> started new task:
                                            <span class="accent">Dashboard UI design.</span>. </p>
                                    </div>
                                </a>
                            </li>
                            <li>
                                <a href="" class="notification-item">
                                    <div class="img-col">
                                        <div class="img" style="background-image: url('assets/faces/8.jpg')"></div>
                                    </div>
                                    <div class="body-col">
                                        <p>
                                            <span class="accent">Andy Nouman</span> deployed new version of
                                            <span class="accent">NodeJS REST Api V3</span>
                                        </p>
                                    </div>
                                </a>
                            </li>
                        </ul>
                        <footer>
                            <ul>
                                <li>
                                    <a href=""> View All </a>
                                </li>
                            </ul>
                        </footer>
                    </div>
                </li>
                <li class="profile dropdown">
                    <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button"
                       aria-haspopup="true" aria-expanded="false">
                        <div class="img"
                             style="background-image: url('https://avatars3.githubusercontent.com/u/3959008?v=3&s=40')"></div>
                        <span class="name">{{ request.session.username }}</span>
                    </a>
                    <div class="dropdown-menu profile-dropdown-menu" aria-labelledby="dropdownMenu1">
                        <a class="dropdown-item" href="{% url 'profiles:show_self' %}">
                            <i class="fa fa-user icon"></i> Profile </a>
                        <a class="dropdown-item" href="">
                            <i class="fa fa-bell icon"></i> Notifications </a>
                        <a class="dropdown-item" href="#">
                            <i class="fa fa-gear icon"></i> Settings </a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{% url 'accounts:logout' %}">
                            <i class="fa fa-power-off icon"></i> Logout </a>
                    </div>
                </li>
            </ul>
        </div>
    </header>

{% endblock %}

src/templates/base/partials/_sidebar.html
{% block sidebar %}

    <aside class="sidebar">
        <div class="sidebar-container">
            <div class="sidebar-header">
                <div class="brand">
                    <div class="logo">
                        <span class="l l1"></span>
                        <span class="l l2"></span>
                        <span class="l l3"></span>
                        <span class="l l4"></span>
                        <span class="l l5"></span>
                    </div>
                    PY Nginx
                </div>
            </div>
            <nav class="menu">
                <ul class="sidebar-menu metismenu" id="sidebar-menu">
                    <li class="active">
                        <a href="{% url 'home' %}">
                            <i class="fa fa-home"></i> Dashboard </a>
                    </li>
                    <li>
                        <a href="">
                            <i class="fa fa-sitemap"></i> Sites
                            <i class="fa arrow"></i>
                        </a>
                        <ul class="sidebar-nav">
                            <li>
                                <a href="{% url 'sites:index' %}"> All Sites</a>
                            </li>
                            <li>
                                <a href="{% url 'sites:create_site' %}"> Add Site </a>
                            </li>
                        </ul>
                    </li>
                    <li>
                        <a href="">
                            <i class="fa fa-bar-chart"></i> Charts
                            <i class="fa arrow"></i>
                        </a>
                        <ul class="sidebar-nav">
                            <li>
                                <a href="charts-flot.html"> Flot Charts </a>
                            </li>
                            <li>
                                <a href="charts-morris.html"> Morris Charts </a>
                            </li>
                        </ul>
                    </li>
                    <li>
                        <a href="">
                            <i class="fa fa-table"></i> Tables
                            <i class="fa arrow"></i>
                        </a>
                        <ul class="sidebar-nav">
                            <li>
                                <a href="static-tables.html"> Static Tables </a>
                            </li>
                            <li>
                                <a href="responsive-tables.html"> Responsive Tables </a>
                            </li>
                        </ul>
                    </li>
                    <li>
                        <a href="forms.html">
                            <i class="fa fa-pencil-square-o"></i> Forms </a>
                    </li>
                    <li>
                        <a href="">
                            <i class="fa fa-desktop"></i> UI Elements
                            <i class="fa arrow"></i>
                        </a>
                        <ul class="sidebar-nav">
                            <li>
                                <a href="buttons.html"> Buttons </a>
                            </li>
                            <li>
                                <a href="cards.html"> Cards </a>
                            </li>
                            <li>
                                <a href="typography.html"> Typography </a>
                            </li>
                            <li>
                                <a href="icons.html"> Icons </a>
                            </li>
                            <li>
                                <a href="grid.html"> Grid </a>
                            </li>
                        </ul>
                    </li>
                    <li>
                        <a href="">
                            <i class="fa fa-file-text-o"></i> Pages
                            <i class="fa arrow"></i>
                        </a>
                        <ul class="sidebar-nav">
                            <li>
                                <a href="login.html"> Login </a>
                            </li>
                            <li>
                                <a href="signup.html"> Sign Up </a>
                            </li>
                            <li>
                                <a href="reset.html"> Reset </a>
                            </li>
                            <li>
                                <a href="error-404.html"> Error 404 App </a>
                            </li>
                            <li>
                                <a href="error-404-alt.html"> Error 404 Global </a>
                            </li>
                            <li>
                                <a href="error-500.html"> Error 500 App </a>
                            </li>
                            <li>
                                <a href="error-500-alt.html"> Error 500 Global </a>
                            </li>
                        </ul>
                    </li>
                    <li>
                        <a href="">
                            <i class="fa fa-sitemap"></i> Menu Levels
                            <i class="fa arrow"></i>
                        </a>
                        <ul class="sidebar-nav">
                            <li>
                                <a href="#"> Second Level Item
                                    <i class="fa arrow"></i>
                                </a>
                                <ul class="sidebar-nav">
                                    <li>
                                        <a href="#"> Third Level Item </a>
                                    </li>
                                    <li>
                                        <a href="#"> Third Level Item </a>
                                    </li>
                                </ul>
                            </li>
                            <li>
                                <a href="#"> Second Level Item </a>
                            </li>
                            <li>
                                <a href="#"> Second Level Item
                                    <i class="fa arrow"></i>
                                </a>
                                <ul class="sidebar-nav">
                                    <li>
                                        <a href="#"> Third Level Item </a>
                                    </li>
                                    <li>
                                        <a href="#"> Third Level Item </a>
                                    </li>
                                    <li>
                                        <a href="#"> Third Level Item
                                            <i class="fa arrow"></i>
                                        </a>
                                        <ul class="sidebar-nav">
                                            <li>
                                                <a href="#"> Fourth Level Item </a>
                                            </li>
                                            <li>
                                                <a href="#"> Fourth Level Item </a>
                                            </li>
                                        </ul>
                                    </li>
                                </ul>
                            </li>
                        </ul>
                    </li>
                    <li>
                        <a href="https://github.com/modularcode/modular-admin-html">
                            <i class="fa fa-github-alt"></i> Theme Docs </a>
                    </li>
                </ul>
            </nav>
        </div>
        <footer class="sidebar-footer">
            <ul class="sidebar-menu metismenu" id="customize-menu">

            </ul>
        </footer>
    </aside>
    <div class="sidebar-overlay" id="sidebar-overlay"></div>
    <div class="sidebar-mobile-menu-handle" id="sidebar-mobile-menu-handle"></div>
    <div class="mobile-menu-handle"></div>

{% endblock %}