src/accounts/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^login/$', views.LoginView.as_view(), name="login"),
    url(r'^logout/$', views.LogoutView.as_view(), name='logout'),
    url(r'^signup/$', views.SignUpView.as_view(), name='signup'),
    url(r'^password-change/$', views.PasswordChangeView.as_view(),
        name='password-change'),
    url(r'^password-reset/$', views.PasswordResetView.as_view(),
        name='password-reset'),
    url(r'^password-reset-done/$', views.PasswordResetDoneView.as_view(),
        name='password-reset-done'),
    url(r'^password-reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$$',
        views.PasswordResetConfirmView.as_view(),  # NOQA
        name='password-reset-confirm'),
]

src/pynginx/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
import profiles.urls
import accounts.urls
import dashboard.urls
import sites.urls
from . import views

urlpatterns = [
    url(r'^$', views.HomePage.as_view(), name='home'),
    url(r'^about/$', views.AboutPage.as_view(), name='about'),
    url(r'^users/', include(profiles.urls, namespace='profiles')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include(accounts.urls, namespace='accounts')),
    url(r'^dashboard/', include(dashboard.urls, namespace='dashboard')),
    url(r'^sites/', include(sites.urls, namespace='sites')),
]

# User-uploaded files like profile pics need to be served in development
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Include django debug toolbar if DEBUG is on
if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

src/sites/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.SiteIndex.as_view(), name='index'),
    url(r'^create/$', views.SiteCreate.as_view(), name='create_site'),
    url(r'^update/(?P<pk>\d+)/$', views.SiteUpdate.as_view(), name='update_site'),
    url(r'^delete/(?P<pk>\d+)/$', views.SiteDelete.as_view(), name='delete_site'),

]

src/accounts/models.py
from django.db import models

# Create your models here.

src/accounts/forms.py
from __future__ import unicode_literals
from django.contrib.auth.forms import AuthenticationForm
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Div, Submit, HTML, Button, Row, Field
from crispy_forms.bootstrap import AppendedText, PrependedText, FormActions
from authtools import forms as authtoolsforms
from django.contrib.auth import forms as authforms
from django.core.urlresolvers import reverse


class LoginForm(AuthenticationForm):
    remember_me = forms.BooleanField(required=False, initial=False)

    def __init__(self, *args, **kwargs):
        super(LoginForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.fields["username"].widget.input_type = "email"  # ugly hack

        self.helper.layout = Layout(
            Field('username', placeholder="Enter Email", autofocus="", css_class="underlined"),
            Field('password', placeholder="Enter Password", css_class="underlined"),
            HTML('<a href="{}">Forgot Password?</a>'.format(
                reverse("accounts:password-reset"))),
            Field('remember_me'),
            Submit('sign_in', 'Log in',
                   css_class="btn btn-lg btn-primary btn-block"),
        )


class SignupForm(authtoolsforms.UserCreationForm):

    def __init__(self, *args, **kwargs):
        super(SignupForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.fields["email"].widget.input_type = "email"  # ugly hack

        self.helper.layout = Layout(
            Field('email', placeholder="Enter Email", autofocus=""),
            Field('name', placeholder="Enter Full Name"),
            Field('password1', placeholder="Enter Password"),
            Field('password2', placeholder="Re-enter Password"),
            Submit('sign_up', 'Sign up', css_class="btn-warning"),
        )


class PasswordChangeForm(authforms.PasswordChangeForm):

    def __init__(self, *args, **kwargs):
        super(PasswordChangeForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()

        self.helper.layout = Layout(
            Field('old_password', placeholder="Enter old password",
                  autofocus=""),
            Field('new_password1', placeholder="Enter new password"),
            Field('new_password2', placeholder="Enter new password (again)"),
            Submit('pass_change', 'Change Password', css_class="btn-warning"),
        )


class PasswordResetForm(authtoolsforms.FriendlyPasswordResetForm):

    def __init__(self, *args, **kwargs):
        super(PasswordResetForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()

        self.helper.layout = Layout(
            Field('email', placeholder="Enter email",
                  autofocus=""),
            Submit('pass_reset', 'Reset Password', css_class="btn-warning"),
        )


class SetPasswordForm(authforms.SetPasswordForm):
    def __init__(self, *args, **kwargs):
        super(SetPasswordForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()

        self.helper.layout = Layout(
            Field('new_password1', placeholder="Enter new password",
                  autofocus=""),
            Field('new_password2', placeholder="Enter new password (again)"),
            Submit('pass_change', 'Change Password', css_class="btn-warning"),
        )

src/accounts/views.py
from __future__ import unicode_literals
from django.core.urlresolvers import reverse_lazy
from django.views import generic
from django.contrib.auth import get_user_model, get_user
from django.contrib import auth
from django.contrib import messages
from authtools import views as authviews
from braces import views as bracesviews
from django.conf import settings
from . import forms

User = get_user_model()


class LoginView(bracesviews.AnonymousRequiredMixin,
                authviews.LoginView):
    template_name = "accounts/login.html"
    form_class = forms.LoginForm

    def form_valid(self, form):
        redirect = super(LoginView, self).form_valid(form)
        remember_me = form.cleaned_data.get('remember_me')
        current_user = get_user(self.request)
        self.request.session['username'] = current_user.name
        if remember_me is True:
            ONE_MONTH = 30 * 24 * 60 * 60
            expiry = getattr(settings, "KEEP_LOGGED_DURATION", ONE_MONTH)
            self.request.session.set_expiry(expiry)
        return redirect


class LogoutView(authviews.LogoutView):
    url = reverse_lazy('accounts:login')


class SignUpView(bracesviews.AnonymousRequiredMixin,
                 bracesviews.FormValidMessageMixin,
                 generic.CreateView):
    form_class = forms.SignupForm
    model = User
    template_name = 'accounts/signup.html'
    success_url = reverse_lazy('home')
    form_valid_message = "You're signed up!"

    def form_valid(self, form):
        r = super(SignUpView, self).form_valid(form)
        username = form.cleaned_data["email"]
        password = form.cleaned_data["password1"]
        user = auth.authenticate(email=username, password=password)
        auth.login(self.request, user)
        return r


class PasswordChangeView(authviews.PasswordChangeView):
    form_class = forms.PasswordChangeForm
    template_name = 'accounts/password-change.html'
    success_url = reverse_lazy('home')

    def form_valid(self, form):
        form.save()
        messages.success(self.request,
                         "Your password was changed, "
                         "hence you have been logged out. Please relogin")
        return super(PasswordChangeView, self).form_valid(form)


class PasswordResetView(authviews.PasswordResetView):
    form_class = forms.PasswordResetForm
    template_name = 'accounts/password-reset.html'
    success_url = reverse_lazy('accounts:password-reset-done')
    subject_template_name = 'accounts/emails/password-reset-subject.txt'
    email_template_name = 'accounts/emails/password-reset-email.html'


class PasswordResetDoneView(authviews.PasswordResetDoneView):
    template_name = 'accounts/password-reset-done.html'


class PasswordResetConfirmView(authviews.PasswordResetConfirmAndLoginView):
    template_name = 'accounts/password-reset-confirm.html'
    form_class = forms.SetPasswordForm

src/accounts/templates/accounts/auth_base.html
<!DOCTYPE html>
<html lang="en">
{% load staticfiles %}
{% load thumbnail %}

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="{% block description %}{% endblock description %}">
    <meta name="author" content="Arun Ravindran">
    <link rel="shortcut icon" href="{% static 'site/ico/favicon.ico' %}">

    <title>{% block title %}{% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'modularadmin/css/vendor.css' %}" rel="stylesheet">
    <link href="{% static 'modularadmin/css/app-blue.css' %}" rel="stylesheet">

    <!-- Custom styles for this site -->
    {% block styles %}

    {% endblock styles %}

    <!-- Custom tags for the head tag -->
    {% block extrahead %}{% endblock extrahead %}

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
</head>

<body>
<div class="auth">
    <div class="auth-container">
        <div class="card">
            <header class="auth-header">
                <h1 class="auth-title">
                    <div class="logo">
                        <span class="l l1"></span>
                        <span class="l l2"></span>
                        <span class="l l3"></span>
                        <span class="l l4"></span>
                        <span class="l l5"></span>
                    </div>
                    ModularAdmin
                </h1>
            </header>
            {% load crispy_forms_tags %}


            {% block container %}
                <div class="auth-content">
                <p class="text-center">{% block form_heading %}{% endblock %}</p>
                {% block form %}
                {% endblock %}


            {% endblock container %}

src/accounts/templates/accounts/login.html
{% extends "accounts/auth_base.html" %}

{% load crispy_forms_tags %}

{% block title %}{{ block.super }}Log In{% endblock %}

{% block form_heading %}Please Log In{% endblock %}

{% block form %}
    {% crispy form %}
    <div class="form-message">
        <p>
            Don't have an account? <a href="{% url 'accounts:signup' %}">Sign up</a>.
        </p>
    </div>
{% endblock form %}

src/accounts/templates/accounts/password-change.html
{% extends "accounts/auth_base.html" %}

{% load crispy_forms_tags %}

{% block title %}{{ block.super }}Password Change{% endblock %}

{% block form_heading %}Password Change{% endblock %}

{% block form %}
    {% crispy form %}
{% endblock form %}

src/accounts/templates/accounts/password-reset-confirm.html
{% extends "accounts/auth_base.html" %}

{% load crispy_forms_tags %}

{% block title %}{{ block.super }}Password Change{% endblock %}

{% block form_heading %}Password Change{% endblock %}

{% block form %}
    {% crispy form %}
{% endblock form %}

src/accounts/templates/accounts/password-reset-done.html
{% extends "accounts/auth_base.html" %}

{% load crispy_forms_tags %}

{% block title %}{{ block.super }}Password Reset Done{% endblock %}

{% block form_heading %}Password Reset Email Sent{% endblock %}

{% block form %}
    <div class="form-message">
        <p>
            Please check your mail. You would have received a password reset mail from us.
        </p>
    </div>
{% endblock form %}

src/accounts/templates/accounts/password-reset.html
{% extends "accounts/auth_base.html" %}

{% load crispy_forms_tags %}

{% block title %}{{ block.super }}Password Reset{% endblock %}

{% block form_heading %}Password Reset{% endblock %}

{% block form %}
    {% crispy form %}
{% endblock form %}

src/accounts/templates/accounts/signup.html
{% extends "accounts/auth_base.html" %}

{% load crispy_forms_tags %}

{% block title %}{{ block.super }}Sign Up{% endblock %}

{% block form_heading %}Signing Up is Free{% endblock %}

{% block form %}
    {% crispy form %}

    <div class="form-message">
        <p>
            Already signed up? <a href="{% url 'accounts:login' %}">Log in</a>.
        </p>
    </div>
{% endblock form %}